# Generated by Django 3.0.7 on 2020-07-22 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200722_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='users',
        ),
        migrations.AddField(
            model_name='likes',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='likes',
            name='post',
            field=models.ManyToManyField(related_name='lpost', to='network.Post'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ManyToManyField(related_name='luser', to=settings.AUTH_USER_MODEL),
        ),
    ]
