# Generated by Django 3.0.7 on 2020-07-25 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20200724_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='lpost', to='network.Post'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='luser', to=settings.AUTH_USER_MODEL),
        ),
    ]
