# Generated by Django 3.0.7 on 2020-07-25 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20200725_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='post',
            field=models.ManyToManyField(blank=True, to='network.Post'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
