# Generated by Django 3.0.7 on 2020-07-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='follower',
        ),
        migrations.AddField(
            model_name='following',
            name='followerId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='following',
            name='followingId',
            field=models.IntegerField(null=True),
        ),
    ]
