# Generated by Django 3.0.8 on 2020-07-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20200726_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scope',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
