# Generated by Django 3.0.8 on 2020-08-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20200801_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='recipient',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
